#!/bin/sh                              
#Test run script    
                  
make run                      \
OPT="+UVM_VERBOSITY=UVM_MEDIUM     \
+inp_num_tx=10000               \
+watchdog_timer=1                 \
"                                  \
GUI=0         
                   
